// swift-tools-version: 5.7

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "OnboardPreviewApp",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "OnboardPreviewApp",
            targets: ["OnboardPreviewModule"],
            bundleIdentifier: "jp.godapp.app.ios.OnboardPreviewApp",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .smiley),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(name: "God", path: "../../Packages/GodPackage")
    ],
    targets: [
        .executableTarget(
            name: "OnboardPreviewModule",
            path: "."
        )
    ]
)