name: Auto Approve

on:
  pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr review --approve "$PR_URL"
        if: github.actor == 'tomokisun' || github.actor == 'renovate[bot]'
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
