name: CI

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: xcodebuild -resolvePackageDependencies -scheme "App (Staging project)"
      - run: xcodebuild build -workspace pine.xcworkspace -scheme "App (Staging project)" -sdk iphonesimulator
