name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - App/**/*
      - Packages/**/*
      - PreviewApp/**/*
      - .github/workflows/ci.yml
  pull_request:
    paths:
      - App/**/*
      - Packages/**/*
      - PreviewApp/**/*
      - .github/workflows/ci.yml

env:
  PLATFORM_IOS: iOS Simulator,name=iPhone 15 Pro,OS=17.0
  FILE_FIREBASE_STAGING: ${{ secrets.FILE_FIREBASE_STAGING }}
  FILE_FIREBASE_PRODUCTION: ${{ secrets.FILE_FIREBASE_PRODUCTION }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: ls /Applications
      - run: sudo xcode-select -s /Applications/Xcode_15.0.0.app
      - uses: irgaly/xcode-cache@v1
        with:
          key: xcode-cache-deriveddata-${{ github.workflow }}-${{ github.sha }}
          restore-keys: xcode-cache-deriveddata-${{ github.workflow }}-
      - run: make bootstrap
      - run: xcodebuild build -workspace God.xcworkspace -scheme "App (Staging project)" -sdk iphonesimulator
