name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - App/**/*
      - Packages/**/*
      - PreviewApp/**/*
  pull_request:
    paths:
      - App/**/*
      - Packages/**/*
      - PreviewApp/**/*

env:
  PLATFORM_IOS: iOS Simulator,name=iPhone 14 Pro,OS=16.2
  FILE_FIREBASE_STAGING: ${{ secrets.FILE_FIREBASE_STAGING }}
  FILE_FIREBASE_PRODUCTION: ${{ secrets.FILE_FIREBASE_PRODUCTION }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - run: make bootstrap
      - uses: actions/cache@v3
        with:
          path: SourcePackages
          key: ${{ runner.os }}-xcworkspace-${{ hashFiles('God.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
      - run: xcodebuild -workspace God.xcworkspace -resolvePackageDependencies -scheme "App (Staging project)" -clonedSourcePackagesDirPath SourcePackages
      - run: xcodebuild -workspace God.xcworkspace -scheme "App (Staging project)" build -sdk iphonesimulator -clonedSourcePackagesDirPath SourcePackages
