name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  PLATFORM_IOS: iOS Simulator,name=iPhone 14 Pro,OS=16.2
  FILE_FIREBASE_STAGING: ${{ secrets.FILE_FIREBASE_STAGING }}
  FILE_FIREBASE_PRODUCTION: ${{ secrets.FILE_FIREBASE_PRODUCTION }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: build and test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: make bootstrap
      - uses: actions/cache@v3
        with:
          path: SourcePackages
          key: ${{ runner.os }}-xcworkspace-${{ hashFiles('God.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
      - run: xcodebuild -resolvePackageDependencies -scheme "App (Staging project)" -clonedSourcePackagesDirPath SourcePackages
      - run: xcodebuild -workspace God.xcworkspace -scheme "App (Staging project)" build -sdk iphonesimulator -clonedSourcePackagesDirPath SourcePackages
      - run: xcodebuild -workspace God.xcworkspace -scheme "App (Staging project)" test -testPlan App -destination platform="${{ env.PLATFORM_IOS }}" -clonedSourcePackagesDirPath SourcePackages
