name: dgraph

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*/Package.swift'
      - '.github/workflows/dgraph.yml'

jobs:
  dgraph:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - run: make dgraph
      - run: make format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run dgraph
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
