name: dgraph

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*/Package.swift'

jobs:
  dgraph:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: BuildTools/DependenciesGraph/.build
          key: ${{ runner.os }}-DependenciesGraph-${{ hashFiles('BuildTools/DependenciesGraph/Package.resolved') }}
      - run: make dgraph
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run dgraph
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
