name: dgraph

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*/Package.swift'

jobs:
  dgraph:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: BuildTools/DependenciesGraph/.build
          key: ${{ runner.os }}-DependenciesGraph-${{ hashFiles('BuildTools/DependenciesGraph/Package.resolved') }}
      - run: make dgraph
      - continue-on-error: true
        uses: peter-evans/create-pull-request@v5
        id: create-pr
        with:
          delete-branch: true
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch-suffix: short-commit-hash
          commit-message: Run dgraph
          title: Run dgraph
      - continue-on-error: true
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ steps.create-pr.outputs.pull-request-url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}