name: Format

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.swift'
      - '.github/workflows/format.yml'

jobs:
  swift-format:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: BuildTools/SwiftFormatTool/.build
          key: ${{ runner.os }}-SwiftFormatTool-${{ hashFiles('BuildTools/SwiftFormatTool/Package.resolved') }}
      - run: make format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run swift-format
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
