name: Renovate

on:
  push:
    branches:
      - 'renovate/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - run: xcodebuild -resolvePackageDependencies -scheme "App (Staging project)"
      - run: swift build -c release --package-path ./BuildTools/DependenciesGraph --product dgraph
      - run: swift build -c release --package-path ./BuildTools/SwiftFormatTool --product swiftformat
      - run: swift build -c release --package-path ./BuildTools/XCTemplateInstallerTool --product XCTemplateInstaller
      - continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "chore: 🤖 update package.resolved"
          git push
