name: Renovate

on:
  push:
    branches:
      - 'renovate/**'

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.file_changes.outputs.files }}
    steps:
      - uses: actions/checkout@v3
      - uses: trilom/file-changes-action@v1.2.4
        id: file_changes
  update:
    runs-on: ubuntu-latest
    needs: precheck
    if: contains(fromJson(needs.precheck.outputs.files_changed), 'Package.resolved') == false
    steps:
      - uses: actions/checkout@v3
      - run: xcodebuild -resolvePackageDependencies -workspace "$workspace" -scheme "$scheme"
      - run: xcodebuild -resolvePackageDependencies -scheme "App (Staging project)"
      - continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "chore: 🤖 update package.resolved"
          git push
