name: Renovate

on:
  push:
    branches:
      - 'renovate/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: sudo xcode-select -s /Applications/Xcode_15.0.1.app
      - run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - run: xcodebuild -workspace God.xcworkspace -resolvePackageDependencies -scheme "App (Staging project)" -skipMacroValidation
      - run: swift build -c release --package-path ./BuildTools/ApolloTool
      - run: swift build -c release --package-path ./BuildTools/DependenciesGraph --product dgraph
      - run: swift build -c release --package-path ./BuildTools/SwiftFormatTool --product swiftformat
      - run: swift build -c release --package-path ./BuildTools/XCTemplateInstallerTool --product XCTemplateInstaller
      - continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "chore: 🤖 update package.resolved"
          git push
