name: Renovate

on:
  push:
    branches:
      - 'renovate/**'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: xcodebuild -resolvePackageDependencies -scheme "App (Staging project)"
      - continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "chore: 🤖 update package.resolved"
          git push
